# Generated by Django 2.2.6 on 2020-09-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='commodity',
            fields=[
                ('commodityID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('transactionType', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('studentID', models.IntegerField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=10)),
                ('phoneNumber', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=10)),
                ('college', models.CharField(max_length=20)),
                ('major', models.CharField(max_length=20)),
                ('dormitory', models.CharField(max_length=20)),
            ],
        ),
    ]
