# Generated by Django 2.2.6 on 2020-09-29 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='commodity',
            new_name='commoditys',
        ),
    ]
