# Generated by Django 2.2.6 on 2020-09-30 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20200930_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='commodity',
            fields=[
                ('commodityID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('transactionType', models.CharField(max_length=10)),
            ],
        ),
    ]
