# Generated by Django 2.2.6 on 2020-10-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0013_auto_20201002_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='studentID',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
