# Generated by Django 2.2.6 on 2020-10-03 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0016_auto_20201003_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commodity',
            old_name='lastestModified',
            new_name='latestModified',
        ),
    ]
