# Generated by Django 3.1.1 on 2020-12-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0017_auto_20201003_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='commodityID',
            field=models.AutoField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='studentID',
            field=models.AutoField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
