# Generated by Django 3.1.1 on 2020-12-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0018_auto_20201219_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='avatar',
            field=models.ImageField(default='avatars/default.png', upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='commodityID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='user',
            name='studentID',
            field=models.CharField(default='', max_length=12, primary_key=True, serialize=False),
        ),
    ]
